#!/bin/python
import socket
import sys

def scan():
    arg = sys.argv
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.settimeout(3)
    host = socket.gethostbyname(arg[1])
    port_input = arg[2]
    version = ""
    if "-v" in sys.argv:
        print("\033[1;32mPort\t\tStatus\t\tService\t\tVersion")
        print("\033[1;34m----\t\t------\t\t-------\t\t-------\033[0m")
    else:
        print("\033[1;32mPort\t\tStatus\t\tService")
        print("\033[1;34m----\t\t------\t\t-------\033[0m")

    if '-' in port_input:
        start, end = map(int, port_input.split('-'))
        for port in range(start, end + 1):
            check_port(sock, host, port)
    else:
        port = int(port_input)
        check_port(sock, host, port)

    sock.close()

def check_port(sock, host, port):
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        result = sock.connect_ex((host, port))

        if result == 0:
            service = "Unknown"
            version = "Unknown"

            try:
                service = socket.getservbyport(port, "tcp")

                sock.settimeout(5)
                version = sock.recv(1024).decode().strip()
            except socket.timeout:
                version = "No banner"
            except Exception as e:
                version = "Error: " + str(e)
            if "-v" in sys.argv:
                    print(f"{port}/tcp\t\t\033[1;32mOPEN\t\t\033[1;32m{service}\t\t\033[1;37m{version}\033[0m")
            else:
                    print(f"{port}/tcp\t\t\033[1;32mOPEN\t\t\033[1;32m{service}\t\t\033[0m")
        else:
              if '-' in sys.argv:
                        print("\r")

    except Exception as e:
        print(f"Error scanning port {port}: {str(e)}")

    finally:
        sock.close()

if __name__ == "__main__":
    try:
        scan()
    except KeyboardInterrupt:
        sys.exit(0)
    except Exception as e:
        print(f"Error: {str(e)}")
        sys.exit(1)

